apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay-operator
  namespace: {{ .Release.Namespace }}
spec:
  channel: {{ .Values.subscriptionChannel }}
  installPlanApproval: {{ .Values.subscriptionApproval }}
  name: quay-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
