apiVersion: v1
kind: Secret
metadata:
  name: external-dns-credentials-external-dns
  namespace: external-dns-operator
stringData:
  credentials: |
    [default]
    aws_access_key_id = {{ .Values.awsAccessKeyId }}
    aws_secret_access_key = {{ .Values.awsSecretAccessKey }}
