apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-volume
  namespace: openshift-cluster-csi-drivers
spec:
  storageClassName: efs-csi
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
