apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-sandboxed-containers-operator
  namespace: {{ .Release.Namespace }}
spec:
  targetNamespaces:
  - {{ .Release.Namespace }}
