# This secret must exist or Velero pods won't start.
# None of the values in this secret are actually used by the core Velero.
# Only the Velero vSphere plugin really uses this secret.
apiVersion: v1
kind: Secret
metadata:
  name: cloud-credentials
  namespace: {{ .Release.Namespace }}
stringData:
  data: |
    [default]
    aws_access_key_id     = {{ .Values.s3Storage.awsAccessKeyId }}
    aws_secret_access_key = {{ .Values.s3Storage.awsSecretAccessKey }}
