apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: nginx-ingress-operator
  namespace: nginx-ingress-operator
spec:
  channel: alpha
  installPlanApproval: {{ .Values.subscriptionApproval }}
  name: nginx-ingress-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
