apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.subscriptionName }}
  namespace: openshift-operators
spec:
  channel: latest
  installPlanApproval: {{ .Values.subscriptionApproval }}
  name: openshift-pipelines-operator-rh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
