apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hashicorp-vault-test
  namespace: {{ .Release.Namespace }}
spec:
  secretName: hashicorp-vault-test
  issuerRef:
    kind: ClusterIssuer
    name: hashicorp-vault
  commonName: {{ .Values.certificate.dnsName }}
  dnsNames:
  - {{ .Values.certificate.dnsName }}
