apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: cert-manager
  name: hashicorp-vault-token-static
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/service-account-token
