apiVersion: v1
kind: Secret
metadata:
  name: broker-credentials-secret
  namespace: {{ .Release.Namespace }}
stringData:
  AMQ_CLUSTER_PASSWORD: {{ .Values.amqClusterPassword | squote }}
  AMQ_CLUSTER_USER: admin
  AMQ_PASSWORD: {{ .Values.amqPassword | squote }}
  AMQ_USER: admin
