apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: broker
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      ActiveMQArtemis: broker
  endpoints:
  - path: /metrics
    port: console-jolokia
    scheme: http
