apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: external-dns-operator
  namespace: external-dns-operator
spec:
  channel: {{ .Values.subscriptionChannel }}
  installPlanApproval: {{ .Values.subscriptionChannel }}
  name: external-dns-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
